spring:
  application:
    name: "SimpleFlashSale"
  datasource:
    url: jdbc:mysql://localhost:3306/SimpleFlashSale
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/SimpleFlashSale

server:
  port: 8080
  http2:
    enabled: true

keycloak:
  auth-server-url: http://localhost:7080
  realm: SimpleFlashSale
  client-id: SimpleFlashSaleClient
  client-secret: Orm6SyrIN5W3t7mQBjwiH6xjvycZ774e
  admin-username: admin
  admin-password: admin

redis:
  url: redis://localhost:6379

kafka:
  bootstrap-servers: localhost:9092
  producer:
    retries: 3
  topic:
    payment: "payment_orders"