apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashsale-frontend
  namespace: flashsale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: xinningb/flashsale_frontend:v1
        ports:
        - containerPort: 80
