# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Maven wrapper and project files
COPY mvnw pom.xml ./
COPY .mvn .mvn

# Copy the application source code
COPY src ./src

# Build the application using Maven
RUN ./mvnw package -DskipTests

# Copy the built JAR file to the container
RUN cp target/*.jar app.jar

# Expose the application port
EXPOSE 8080
#
# # Set environment variables from application.yml
# ENV SPRING_APPLICATION_NAME=SimpleFlashSale \
#     SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/SimpleFlashSale \
#     SPRING_DATASOURCE_USERNAME=root \
#     SPRING_DATASOURCE_PASSWORD=123456 \
#     SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver \
#     SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect \
#     SPRING_JPA_HIBERNATE_DDL_AUTO=update \
#     SPRING_JPA_SHOW_SQL=true \
#     SPRING_SQL_INIT_MODE=always \
#     SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost:7080/realms/SimpleFlashSale \
#     KEYCLOAK_AUTH_SERVER_URL=http://localhost:7080 \
#     KEYCLOAK_REALM=SimpleFlashSale \
#     KEYCLOAK_CLIENT_ID=SimpleFlashSaleClient \
#     KEYCLOAK_CLIENT_SECRET=Orm6SyrIN5W3t7mQBjwiH6xjvycZ774e \
#     KEYCLOAK_ADMIN_USERNAME=admin \
#     KEYCLOAK_ADMIN_PASSWORD=admin \
#     REDIS_URL=redis://localhost:6379 \
#     KAFKA_BOOTSTRAP_SERVERS=localhost:9092 \
#     KAFKA_TOPIC_PAYMENT=payment_orders

# Define the entrypoint
ENTRYPOINT ["java", "-jar", "app.jar"]
